@UserService.API_HostAddress = http://localhost:8080

GET {{UserService.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{UserService.API_HostAddress}}/api/customer
Content-Type: application/json

{
  "Name": "Moicanso",
  "Email": "moicanso@gmail.com"
}

###

GET {{UserService.API_HostAddress}}/api/customer

###

POST {{UserService.API_HostAddress}}/api/payment
Content-Type: application/json

{
  "From": "2aaa0dc8-90d5-4690-5d30-08de0c30673d",
  "To": "7c7dd0ab-0f03-420c-5d31-08de0c30673d",
  "Amount": 1000,
  "Method": "CreditCard"
}

###
