@UserService.API_HostAddress = http://localhost:8080

GET {{UserService.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{UserService.API_HostAddress}}/api/customer
Content-Type: application/json

{
  "Name": "Ankalaev Owl Face",
  "Email": "ankalaev@gmail.com"
}

###

POST {{UserService.API_HostAddress}}/api/payment/new-payment
Content-Type: application/json

{
  "From": "DD387216-8B80-441D-B71A-08DE12804329",
  "To": "E64FBF44-A476-40CF-B719-08DE12804329",
  "Amount": 500,
  "Method": "CreditCard"
}

###

GET {{UserService.API_HostAddress}}/api/customer/all

###

GET {{UserService.API_HostAddress}}/api/customer/bank-accounts

###
